- name: uninstalled nginx and disable
  hosts: web
  become: yes
  tasks:
  - name: uninstall nginx
    ansible.builtin.dnf:
      name: nginx
      state: absent

  - name: disable nginx service
    ansible.builtin.service:
      name: nginx
      state: stop
      disable: yes    