- name: variables
  hosts: localhost
  vars: #variable declarartion
    course: "ansible"
    trainer: "vasu"
    duration: "10hrs"
  tasks:
  - name: print override info
    vars: #task level variables
      course: "devops"
    ansible.builtin.debug:
      msg: "hi, iam learning {{course}} from trainer {{trainer}}, duration is {{duration}}"


  - name: print info
    ansible.builtin.debug:
      msg: " hi, we are learning {{course}} from trainer {{trainer}}, duration is {{duraion}}"


