- name: variables from prompt
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: please enter username
    private: false
  - name: PASSWORD
    prompt: please enter password
    private: true  
  tasks:
  - name: print info
    ansible.builtin.debug:
      msg: "your user name is {{USERNAME}}, and password is: {{PASSWORD}}"