- name: install package
  hosts: localhost
  become: yes
  tasks:
  - name: install package
    ansible.builtin.dnf:
      name: "{{item}}"
      state: latest
    loop:
    - mysql
    - nginx
    - postfix  