- name: install package
  hosts: localhost
  become: yes
  tasks:
  - name: install package
    ansible.builtin.dnf:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'mysql', state: 'absent'}
    - { name: 'nginx', state: 'absent'}
    - { name: 'postfix', state: 'absent'}  